document.body.appendChild(document.createTextNode(String(window.location))); // alert 1
document.body.appendChild(document.createTextNode(String(window.location))); // alert 2
document.body.appendChild(document.createTextNode(String(window.location))); // alert 3
document.body.appendChild(document.createTextNode(String(window.location))); // alert 4
document.body.appendChild(document.createTextNode(String(window.location))); // alert 5
document.body.appendChild(document.createTextNode(String(window.location))); // alert 6
document.body.appendChild(document.createTextNode(String(window.location))); // alert 7
document.body.appendChild(document.createTextNode(String(window.location))); // alert 8
document.body.appendChild(document.createTextNode(String(window.location))); // alert 9
document.body.appendChild(document.createTextNode(String(window.location))); // alert 10
document.body.appendChild(document.createTextNode(String(window.location))); // alert 11
document.body.appendChild(document.createTextNode(String(window.location))); // alert 12
document.write(window.location); // alert 13
document.write(window.location); // alert 14
document.write(window.location); // alert 15
document.write(window.location); // alert 16
document.write(window.location); // alert 17
document.write(window.location); // alert 18
document.write(window.location); // alert 19
document.write(window.location); // alert 20
document.write(window.location); // alert 21
document.write(window.location); // alert 22
document.write(window.location); // alert 23
document.write(window.location); // alert 24
document.write(window.location); // alert 25
document.write(window.location); // alert 26
document.write(window.location); // alert 27
document.write(window.location); // alert 28
document.write(window.location); // alert 29
document.write(window.location); // alert 30
document.write(window.location); // alert 31
document.write(window.location); // alert 32
document.write(window.location); // alert 33
document.write(window.location); // alert 34
document.write(window.location); // alert 35
document.write(window.location); // alert 36
document.write(window.location); // alert 37
document.write(window.location); // alert 38
document.write(window.location); // alert 39
document.write(window.location); // alert 40
document.write(window.location); // alert 41
document.write(window.location); // alert 42
document.write(window.location); // alert 43
document.write(window.location); // alert 44
document.write(window.location); // alert 45
document.write(window.location); // alert 46
document.write(window.location); // alert 47
document.write(window.location); // alert 48
document.write(window.location); // alert 49
document.write(window.location); // alert 50
document.write(window.location); // alert 51
document.write(window.location); // alert 52
document.write(window.location); // alert 53
document.write(window.location); // alert 54
document.write(window.location); // alert 55
document.write(window.location); // alert 56
document.write(window.location); // alert 57
document.write(window.location); // alert 58
document.write(window.location); // alert 59
document.write(window.location); // alert 60
document.write(window.location); // alert 61
document.write(window.location); // alert 62
document.write(window.location); // alert 63
document.write(window.location); // alert 64
document.write(window.location); // alert 65
document.write(window.location); // alert 66
document.write(window.location); // alert 67
document.write(window.location); // alert 68
document.write(window.location); // alert 69
document.write(window.location); // alert 70
document.write(window.location); // alert 71
document.write(window.location); // alert 72
document.write(window.location); // alert 73
document.write(window.location); // alert 74
document.write(window.location); // alert 75
document.write(window.location); // alert 76
document.write(window.location); // alert 77
document.write(window.location); // alert 78
document.write(window.location); // alert 79
document.write(window.location); // alert 80
document.write(window.location); // alert 81
document.write(window.location); // alert 82
document.write(window.location); // alert 83
document.write(window.location); // alert 84
document.write(window.location); // alert 85
document.write(window.location); // alert 86
document.write(window.location); // alert 87
document.write(window.location); // alert 88
document.write(window.location); // alert 89
document.write(window.location); // alert 90
document.write(window.location); // alert 91
document.write(window.location); // alert 92
document.write(window.location); // alert 93
document.write(window.location); // alert 94
document.write(window.location); // alert 95
document.write(window.location); // alert 96
document.write(window.location); // alert 97
document.write(window.location); // alert 98
document.write(window.location); // alert 99
document.write(window.location); // alert 100
document.write(window.location); // alert 101
document.write(window.location); // alert 102
document.write(window.location); // alert 103
document.write(window.location); // alert 104
document.write(window.location); // alert 105
document.write(window.location); // alert 106
document.write(window.location); // alert 107
document.write(window.location); // alert 108
document.write(window.location); // alert 109
document.write(window.location); // alert 110
document.write(window.location); // alert 111
document.write(window.location); // alert 112
document.write(window.location); // alert 113
document.write(window.location); // alert 114
document.write(window.location); // alert 115
document.write(window.location); // alert 116
document.write(window.location); // alert 117
document.write(window.location); // alert 118
document.write(window.location); // alert 119
document.write(window.location); // alert 120
document.write(window.location); // alert 121
document.write(window.location); // alert 122
document.write(window.location); // alert 123
document.write(window.location); // alert 124
document.write(window.location); // alert 125
document.write(window.location); // alert 126
document.write(window.location); // alert 127
document.write(window.location); // alert 128
document.write(window.location); // alert 129
document.body.appendChild(document.createTextNode(String(window.location))); // alert 130
document.body.appendChild(document.createTextNode(String(window.location))); // alert 131
document.body.appendChild(document.createTextNode(String(window.location))); // alert 132
document.body.appendChild(document.createTextNode(String(window.location))); // alert 133
document.body.appendChild(document.createTextNode(String(window.location))); // alert 134
document.body.appendChild(document.createTextNode(String(window.location))); // alert 135
document.body.appendChild(document.createTextNode(String(window.location))); // alert 136
document.body.appendChild(document.createTextNode(String(window.location))); // alert 137
document.body.appendChild(document.createTextNode(String(window.location))); // alert 138
document.body.appendChild(document.createTextNode(String(window.location))); // alert 139
document.body.appendChild(document.createTextNode(String(window.location))); // alert 140
document.body.appendChild(document.createTextNode(String(window.location))); // alert 141
document.body.appendChild(document.createTextNode(String(window.location))); // alert 142
document.body.appendChild(document.createTextNode(String(window.location))); // alert 143
document.body.appendChild(document.createTextNode(String(window.location))); // alert 144
document.body.appendChild(document.createTextNode(String(window.location))); // alert 145
document.body.appendChild(document.createTextNode(String(window.location))); // alert 146
document.body.appendChild(document.createTextNode(String(window.location))); // alert 147
document.body.appendChild(document.createTextNode(String(window.location))); // alert 148
document.body.appendChild(document.createTextNode(String(window.location))); // alert 149
document.body.appendChild(document.createTextNode(String(window.location))); // alert 150
document.body.appendChild(document.createTextNode(String(window.location))); // alert 151
document.body.appendChild(document.createTextNode(String(window.location))); // alert 152
document.body.appendChild(document.createTextNode(String(window.location))); // alert 153
document.body.appendChild(document.createTextNode(String(window.location))); // alert 154
document.body.appendChild(document.createTextNode(String(window.location))); // alert 155
document.body.appendChild(document.createTextNode(String(window.location))); // alert 156
document.body.appendChild(document.createTextNode(String(window.location))); // alert 157
document.body.appendChild(document.createTextNode(String(window.location))); // alert 158
document.body.appendChild(document.createTextNode(String(window.location))); // alert 159
document.body.appendChild(document.createTextNode(String(window.location))); // alert 160
document.body.appendChild(document.createTextNode(String(window.location))); // alert 161
document.body.appendChild(document.createTextNode(String(window.location))); // alert 162
document.body.appendChild(document.createTextNode(String(window.location))); // alert 163
document.body.appendChild(document.createTextNode(String(window.location))); // alert 164
document.body.appendChild(document.createTextNode(String(window.location))); // alert 165
document.body.appendChild(document.createTextNode(String(window.location))); // alert 166
document.body.appendChild(document.createTextNode(String(window.location))); // alert 167
document.body.appendChild(document.createTextNode(String(window.location))); // alert 168
document.body.appendChild(document.createTextNode(String(window.location))); // alert 169
document.body.appendChild(document.createTextNode(String(window.location))); // alert 170
document.body.appendChild(document.createTextNode(String(window.location))); // alert 171
document.body.appendChild(document.createTextNode(String(window.location))); // alert 172
document.body.appendChild(document.createTextNode(String(window.location))); // alert 173
document.body.appendChild(document.createTextNode(String(window.location))); // alert 174
document.body.appendChild(document.createTextNode(String(window.location))); // alert 175
document.body.appendChild(document.createTextNode(String(window.location))); // alert 176
document.body.appendChild(document.createTextNode(String(window.location))); // alert 177
document.body.appendChild(document.createTextNode(String(window.location))); // alert 178
document.body.appendChild(document.createTextNode(String(window.location))); // alert 179
document.body.appendChild(document.createTextNode(String(window.location))); // alert 180
document.body.appendChild(document.createTextNode(String(window.location))); // alert 181
document.body.appendChild(document.createTextNode(String(window.location))); // alert 182
document.body.appendChild(document.createTextNode(String(window.location))); // alert 183
document.body.appendChild(document.createTextNode(String(window.location))); // alert 184
document.body.appendChild(document.createTextNode(String(window.location))); // alert 185
document.body.appendChild(document.createTextNode(String(window.location))); // alert 186
document.body.appendChild(document.createTextNode(String(window.location))); // alert 187
document.body.appendChild(document.createTextNode(String(window.location))); // alert 188
document.body.appendChild(document.createTextNode(String(window.location))); // alert 189
document.body.appendChild(document.createTextNode(String(window.location))); // alert 180
document.body.appendChild(document.createTextNode(String(window.location))); // alert 191
document.body.appendChild(document.createTextNode(String(window.location))); // alert 192
document.body.appendChild(document.createTextNode(String(window.location))); // alert 193
document.body.appendChild(document.createTextNode(String(window.location))); // alert 194
document.body.appendChild(document.createTextNode(String(window.location))); // alert 195
document.body.appendChild(document.createTextNode(String(window.location))); // alert 196
document.body.appendChild(document.createTextNode(String(window.location))); // alert 197
document.body.appendChild(document.createTextNode(String(window.location))); // alert 198
document.body.appendChild(document.createTextNode(String(window.location))); // alert 199
document.body.appendChild(document.createTextNode(String(window.location))); // alert 200
document.body.appendChild(document.createTextNode(String(window.location))); // alert 201
