name: Artifact test

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - run: New-Item -Path C:\Users\RUNNER~1\AppData\Local\Temp\foo
      - run: New-Item -Path C:\Users\runneradmin\AppData\Local\Temp\bar
      - run: Get-ChildItem -Path C:\Users\RUNNER~1\AppData\Local\Temp
      - run: Get-ChildItem -Path C:\Users\runneradmin\AppData\Local\Temp
