name: "CodeQL analysis"

on: [push]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - run: cat /proc/cpuinfo
    - run: cat /proc/meminfo
