name: "CodeQL analysis"

on: [push]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Initialize CodeQL
      uses: github/codeql-action/init@58a00345495a3ee17fc812514d9c33b3946e7c0d
      with:
        languages: javascript
        config-file: .//codeql-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@58a00345495a3ee17fc812514d9c33b3946e7c0d
