name: "CodeQL analysis"

on: [push]

jobs:
  codeql:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: Warhammer4000/YetAnotherSortingLibrary

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: runner
  
    - run: .\runner\codeql-runner-win.exe init --repository Warhammer4000/YetAnotherSortingLibrary --github-url https://github.com --github-auth ${{ github.token }} --languages csharp
      shell: powershell

    - run: .\runner\codeql-runner-win.exe autobuild
      shell: powershell

    - run: .\runner\codeql-runner-win.exe analyze --repository Warhammer4000/YetAnotherSortingLibrary --github-url https://github.com --github-auth ${{ github.token }} --commit ${{ github.sha }} --ref ${{ github.ref }} --no-upload
      shell: powershell
