name: Mask test

on:
  push:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello"
     - run: echo "::add-mask::Hello"
     - run: echo "Hello"
 
  jobB:
    runs-on: ubuntu-latest
    needs:
    - jobA
    steps:
     - run: echo "Hello"
     - run: echo "::add-mask::Hello"
     - run: echo "Hello"
