name: Matrix test

on:
  push:

jobs:
  jobA:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.foo.outputs.foo }}
    steps:
     - name: foo
       shell: node {0}
       run: |
         const foo = [
           [
             {
               foo: "aa",
               bar: "bb"
             }
           ],
           [
             {
               foo: "cc",
               bar: "dd"
             },
             {
               foo: "ee",
               bar: "ff"
             }
           ]
         ];
         console.log(`::set-output name=foo::${JSON.stringify(foo)}`);
 
  jobB:
    runs-on: ubuntu-latest
    needs:
    - jobA
    strategy:
      matrix:
        foo: ${{ fromJSON(needs.jobA.outputs.foo) }}
    steps:
     - run: echo "${{ toJSON(matrix.foo) }}"
     - run: echo "${{ matrix.foo[0].foo }}"
