name: Matrix test

on:
  push:

jobs:
  jobA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['foo', 'bar']
    steps:
     - run: echo "${{ matrix.x }}"
     - run: echo "${{ matrix.x == "bar" }}"
