name: Matrix test

on:
  push:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: |
          sleep 120
          echo "### Hello after sleeping :grin:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      
  jobB:
    runs-on: ubuntu-latest
    steps:
      - run: echo "### Hello from another job! :heart:" >> $GITHUB_STEP_SUMMARY
